services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Openagenda\Openagenda\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  Openagenda\Openagenda\Controller\OpenagendaController:
    public: true
